[alias]
xtask = "run --manifest-path xtask/Cargo.toml --target x86_64-pc-windows-msvc --"

[build]
target = "thumbv8m.main-none-eabihf"

[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --chip STM32H563VITx"
rustflags = [
  "-C", "link-arg=-Tlink.x",
]
