[package]
name = "druzhba-front-panel-controller"
version = "0.1.0"
authors = ["Zuev"]
edition = "2021"

[features]
default = ["target"]
target = [
    "dep:embassy-stm32",
    "dep:cortex-m",
    "dep:cortex-m-rt",
    "dep:panic-halt",
    "dep:embassy-executor",
]

[dependencies]
druzhba-common = { path = "../common" }

embassy-executor = { workspace = true, optional = true }
embassy-time = { workspace = true }
embassy-sync = { workspace = true }
embassy-futures = { workspace = true }

embassy-stm32 = { version = "0.5", optional = true, features = [
    "stm32h563vi",
    "memory-x",
    "time-driver-any",
    "exti",
    "unstable-pac",
] }

embedded-hal = { workspace = true }
embedded-hal-async = { workspace = true }
embedded-hal-bus = { workspace = true }

cortex-m = { workspace = true, optional = true }
cortex-m-rt = { workspace = true, optional = true }

panic-halt = { workspace = true, optional = true }

ufmt = { workspace = true }
heapless = { workspace = true }
static_cell = { workspace = true }
embedded-graphics = { workspace = true }
embedded-graphics-core = { workspace = true }

[dev-dependencies]
image = { version = "0.25", default-features = false, features = ["png"] }

[target.'cfg(not(target_os = "none"))'.dev-dependencies]
critical-section = { version = "1", features = ["std"] }

[[bin]]
name = "druzhba-front-panel-controller"
path = "src/main.rs"
required-features = ["target"]

[lints.rust]
warnings = "deny"

